import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

/**
 * POST /api/orders/[id]/cancel
 *
 * Allows a customer (non-admin) to cancel a PENDING order they just created.
 * This is called from the Razorpay ondismiss callback when the user closes
 * the payment popup without completing the payment.
 *
 * Security: Requires the razorpayOrderId to be sent in the body. Since this
 * ID is only ever returned to the browser that created the order, and it is
 * a cryptographically random ID generated by Razorpay, it is impossible for
 * anyone else to guess and cancel someone else's order.
 */
export async function POST(req, { params }) {
  try {
    const { id } = params;
    const body = await req.json();
    const { razorpayOrderId } = body;

    if (!id || !razorpayOrderId) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Find the order by its database ID AND verify the razorpayOrderId matches.
    // This double-check means a user cannot cancel someone else's order by
    // just guessing a database ID.
    const order = await prisma.order.findFirst({
      where: {
        id: parseInt(id),
        razorpayOrderId: razorpayOrderId,
      },
    });

    if (!order) {
      return NextResponse.json(
        { success: false, error: 'Order not found' },
        { status: 404 }
      );
    }

    // Only allow cancelling orders that are still PENDING.
    // A PAID order cannot be cancelled this way — that would require an
    // admin-level refund flow.
    if (order.status !== 'PENDING') {
      return NextResponse.json(
        { success: false, error: `Cannot cancel an order with status: ${order.status}` },
        { status: 409 }
      );
    }

    await prisma.order.update({
      where: { id: order.id },
      data: { status: 'CANCELLED' },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error cancelling order:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to cancel order' },
      { status: 500 }
    );
  }
}
